<?php

namespace Mediashare\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopMinersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopMinersRepository extends EntityRepository
{
}
