<?php

namespace Mediashare\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeRepository extends EntityRepository
{
}
