mediashare_app_homepage:
    path:     /
    defaults: { _controller: MediashareAppBundle:Default:index }




topminers:
    path:     /api/getTopMiners
    defaults: { _controller: MediashareAppBundle:Default:topminers }
sitesstates:
    path:     /api/getSiteStats
    defaults: { _controller: MediashareAppBundle:Default:sitestates }
loginuser:
    path:     /api/loginUser/{username}
    defaults: { _controller: MediashareAppBundle:Default:loginuser }


mediashare_app_sitemap:
    path:     /sitemap
    defaults: { _controller: MediashareAppBundle:Default:sitemap }

mediashare_app_sitemapXml:
    path:     /sitemap.xml
    defaults: { _controller: MediashareAppBundle:Default:sitemapXml }
    

mediashare_contact_admin:
    resource: "@MediashareAppBundle/Resources/config/routing/admin_contact.yml"
    prefix:   /admin/contact

mediashare_app_awsindex:
    path:     /awsindex.html
    defaults: { _controller: MediashareAppBundle:Default:awsindex }

mediashare_app_stats:
    path:     /pwstats
    defaults: { _controller: MediashareAppBundle:Default:stats }
