security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Gestion/Concours, role: ROLE_ADMIN }
        # - { path: ^/admin/Concours, role: ROLE_ADMIN }
        - { path: ^/Gestion/Publication/list, role: ROLE_SUPER_ADMIN }
        - { path: ^/Gestion/Publication, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/, role: ROLE_USER }
        # - { path: ^/Gestion/Publication/new, role: ROLE_USER }
        # - { path: ^/Gestion/Publication/edit, role: ROLE_USER }

        # - { path: ^/profile/, role: ROLE_USER }
