<?php

namespace Mediashare\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotesRepository extends EntityRepository
{
}
