mediashare_user_user:
    resource: "@MediashareUserBundle/Resources/config/routing/admin_user.yml"
    prefix:   /user
mediashare_user_profile:
    resource: "@MediashareUserBundle/Resources/config/routing/user.yml"
    prefix:   /profile
